# Generated by Django 3.0.3 on 2020-03-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cnt',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
