# Generated by Django 3.0.3 on 2020-03-19 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_auto_20200319_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='returnable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(default=object, on_delete=django.db.models.deletion.DO_NOTHING, to='shop_app.Product'),
        ),
    ]
