# Generated by Django 3.0.3 on 2020-03-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_remove_purchase_returnable'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='to_return',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
