# Generated by Django 3.0.3 on 2020-03-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_purchase_to_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='returned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='PurchaseReturn',
        ),
    ]
